using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

public class LoadOnClick : MonoBehaviour {

    public void LoadScene(int level)
    {
    	//Debug.Log("where is the level num coming from?" + level);
    	//autogenerated or something but how to get it to connect to the level editor 
    	//need to open it, then go to build settings, and add it that way, and will 
    	//have the right number next to it 
    	
        SceneManager.LoadScene(level);

    }
}
